### ISSUE TITLE
Register this overlay in Layman trough bugs.gentoo.org

### ISSUE THREAD

**Issue by alexws54tk** [yandex-gentoo/overlay#1]
Register this overlay in Layman trough [bugs.gentoo.org](https://bugs.gentoo.org/enter_bug.cgi?product=Gentoo+Infrastructure&component=Gentoo+Overlays).

**Comment by msva** [comment]
https://bugs.gentoo.org/597860

**Comment by msva** [comment]
fixed with https://github.com/gentoo/api-gentoo-org/pull/22
