### ISSUE TITLE
404 for the link about codecs

### ISSUE THREAD

**Issue by kapsh** [yandex-gentoo/overlay#12]
https://github.com/yandex-gentoo/overlay/blob/cb87acb670a802c86b6e2d355f28639a9d9ca35a/www-client/yandex-browser-beta/yandex-browser-beta-18.4.0.2373_p1.ebuild#L126

Link https://yandex.ru/support/browser/working-with-files/video-audio.xml#video-linux is dead.

**Comment by terrible-broom** [comment]
It seems that new valid link is this: https://yandex.ru/support/browser-beta/working-with-files/video.html

**Comment by alexws54tk** [comment]
Closed.
