### ISSUE TITLE
yandex-browser-ffmpeg-codecs building failed

### ISSUE THREAD

**Issue by ProgMiner** [yandex-gentoo/overlay#13]
Hello,

I have a problem with building `yandex-browser-ffmpeg-codecs`.

I attached all requested in error message artifacts:

- `emerge -pqv '=www-plugins/yandex-browser-ffmpeg-codecs-67.0.3396.99::yandex'`:
```
[ebuild  N    ] www-plugins/yandex-browser-ffmpeg-codecs-67.0.3396.99  USE="component-build proprietary-codecs pulseaudio -( -) -pic -x86?"
```
- [build.log](https://github.com/yandex-gentoo/overlay/files/2368613/yandex-browser-ffmpeg-codecs.build.log)
- [`emerge --info '=www-plugins/yandex-browser-ffmpeg-codecs-67.0.3396.99::yandex'`](https://github.com/yandex-gentoo/overlay/files/2368614/yandex-browser-ffmpeg-codecs.info.txt)

Thanks.

**Comment by alexws54tk** [comment]
@ProgMiner 
Eridan, you have the same problem, as well as at guys in an adjacent [issue](https://github.com/yandex-gentoo/overlay/issues/5#issuecomment-417631436).
```shell
[5495/5923] /usr/bin/python2 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="x86_64-pc-linux-gnu-nm" --sofile="./libgfx.so" --tocfile="./libgfx.so.TOC" --output="./libgfx.so"  -- x86_64-pc-linux-gnu-clang++ -shared -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -Wl,--export-dynamic -Wl,-O1 -Wl,--as-needed -o "./libgfx.so" -Wl,-soname="libgfx.so" @"./libgfx.so.rsp"
FAILED: libgfx.so libgfx.so.TOC 
/usr/bin/python2 "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="x86_64-pc-linux-gnu-nm" --sofile="./libgfx.so" --tocfile="./libgfx.so.TOC" --output="./libgfx.so"  -- x86_64-pc-linux-gnu-clang++ -shared -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -Wl,--export-dynamic -Wl,-O1 -Wl,--as-needed -o "./libgfx.so" -Wl,-soname="libgfx.so" @"./libgfx.so.rsp"
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
I cannot confirm since >=llvm-6 and, respectively, >=clang-6 are not builds for me.
With `sys-devel/clang-5.0.2` and `sys-devel/llvm-5.0.2` versions everything builds.

**Comment by ProgMiner** [comment]
Ok, thanks.

I think you could be improve dependencies of package for automatical needed versions installing. I don't know is it supported by Portage, sorry if it isn't.

**Comment by ProgMiner** [comment]
Ok, I tried to build with clang-5.0.2, but building is failed again.

```
[ebuild  N    ] www-plugins/yandex-browser-ffmpeg-codecs-67.0.3396.99  USE="component-build proprietary-codecs pulseaudio -( -) -pic -x86?"
```

[yandex-browser-ffmpeg-codecs.build.log](https://github.com/yandex-gentoo/overlay/files/2373147/yandex-browser-ffmpeg-codecs.build.log)
[yandex-browser-ffmpeg-codecs.info.txt](https://github.com/yandex-gentoo/overlay/files/2373148/yandex-browser-ffmpeg-codecs.info.txt)

**Comment by thankjura** [comment]
Same problem with clang-7.0.0

**Comment by ostinru** [comment]
It seems that patch file wasn't commited to the tree.

> www-plugins/yandex-browser-ffmpeg-codecs-**70.0.3538.102**/files/**chromium-pdfium-stdlib-r0.patch: No such file or directory**

**Comment by programmador** [comment]
+1 "A file listed in the Manifest could not be found"

**Comment by programmador** [comment]
Tried building with `ebuild <filename>.ebuild manifest clean merge` in `/usr/local/portage` after deleting Manifest. Seem's there's a patch missing in the repo:
`/var/tmp/portage/www-plugins/yandex-browser-ffmpeg-codecs-70.0.3538.102/files/chromium-pdfium-stdlib-r0.patch: No such file or di [ !! ]`

**Comment by programmador** [comment]
Btw it's not the only missing patch. Even after commenting out the missing ones there also occurs a patch which can't be applied successfully. So I've stopped my attempts to build it. It seems like the ebuild and patches aren't compatible with the version of chromium mentioned in ebuild file name. Or smth else happened, I don't know.

**Comment by alexws54tk** [comment]
Yeah, patch version not compatible with current version of sources.
Work currently in progress.

**Comment by alexws54tk** [comment]
@ostinru , @programmador I update ebuild for codecs, and fix files issues.

**Comment by STrusov** [comment]
media-video/ffmpeg-chromium-94 works for https://repo.yandex.ru/yandex-browser/rpm/beta/x86_64/yandex-browser-beta-21.11.3.954-1.x86_64.rpm
Just need simlink /opt/yandex/browser-beta/libffmpeg.so -> /usr/lib64/chromium/libffmpeg.so.94

**Comment by ProgMiner** [comment]
For any who will found this dead thread, in this repository there is fresh Yandex browser with fixed libffmpeg: https://github.com/DakEnviy/underworld-overlay

**Comment by STrusov** [comment]
> For any who will find this dead thread, in this repository there is fresh Yandex browser with fixed libffmpeg: https://github.com/DakEnviy/underworld-overlay

As far as I see this downloads prebuilt codecs binary by executing /opt/yandex/browser-beta/update-ffmpeg.
Does it mean that media-video/ffmpeg-chromium-94 does not work?

I have provided https://github.com/yandex-gentoo/overlay/pull/19 however it is not heavily tested nor merged.

**Comment by ProgMiner** [comment]
> > For any who will find this dead thread, in this repository there is fresh Yandex browser with fixed libffmpeg: https://github.com/DakEnviy/underworld-overlay
> 
> As far as I see this version downloads prebuilt codecs binary by executing /opt/yandex/browser-beta/update-ffmpeg. Does it mean that media-video/ffmpeg-chromium-94 does not work?
> 
> I have provided #19 with media-video/ffmpeg-chromium support. However it is not heavily tested nor merged.

Actually, I haven't tested your solution, because this overlay was death for a year and I was forced to use own ebuild for the yandex-browser. But, my opinion is that this is better to use libffmpeg provided by developers rather than build own in order to support compatibility.

**Comment by STrusov** [comment]
> But, my opinion is that this is better to use libffmpeg provided by developers rather than build own in order to support compatibility.

Yandex provides libffmpeg.so which is unable to handle some formats. That is why update-ffmpeg script downloads deb packages built for [Ubuntu](https://pages.browser.yandex.ru/codecs.json). While Gentoo uses media-video/ffmpeg-chromium for www-client/vivaldi.

Unfortunately I have no write permission to this repo nor Yandex Browser in daily use, just occasionally found out that yandex-browser-ffmpeg-codecs is redundant since this issue is solved by Gentoo developers.
