### ISSUE TITLE
Новая версия

### ISSUE THREAD

**Issue by usern1983** [yandex-gentoo/overlay#15]
Пожалуйста обновите ebuild

**Comment by gangstervano** [comment]
1.Не работает видео html5 на некоторых сайтах. Выдаёт ошибку:

desktop-player-adaptive.min.js:13445 Cross-Origin Read Blocking (CORB) blocked cross-origin response ... serrorMessage=MEDIA_ERR_DEFAULT& with MIME type application/json. 
See https://www.chromestatus.com/feature/5629709824032768 for more

2. В новой версии (5.4.28) gentoo не удовлетворены зависимости для www-plugins/yandex-browser-ffmpeg-codecs.

Пожалуйста, обновите ebuild.

**Comment by STrusov** [comment]
Попробуйте 20.4.3.268 
https://github.com/STrusov/yandex-gentoo-overlay

Кодеки не обязтельно собирать, см. /opt/yandex/browser-beta/find_ffmpeg — похоже, скачивает готовый пакт от Ubuntu.

**Comment by alexws54tk** [comment]
@STrusov , да, спасибо, я уже увидел новую версию. Заканчиваю обновлять ебилды.
> Кодеки не обязательно собирать, см. /opt/yandex/browser-beta/find_ffmpeg — похоже, скачивает готовый пакт от Ubuntu.

Нет, `find_ffmpeg` ищет в каталоге браузера подходящую версию `lib/libffmpeg.so`, не более.
Скачивает кодеки новый файл `update_ffmpeg`, но не в подкаталог `lib/`.
