### ISSUE TITLE
EAPI6 is dead

### ISSUE THREAD

**Issue by msva** [yandex-gentoo/overlay#17]
Ref:
https://bugs.gentoo.org/797202
https://qa-reports.gentoo.org/output/repos/yandex.html

**Comment by STrusov** [comment]
I have adapted ebuilds for EAPI7 in 05820ee and 61e6091
However it is a quick hack and not tested as appropriate, since I do not use YB.

**Comment by msva** [comment]
... It is something strange: you've mentioned commits like they're in the repo, they are visible like they were in the repo, but they're not in the master branch...

Can you merge them, please, so @mgorny will close the bug?
