### ISSUE TITLE
Не ставится www-plugins/yandex-browser-ffmpeg-codecs-bin-99.0.4844.84

### ISSUE THREAD

**Issue by an-kuznetsov** [yandex-gentoo/overlay#20]
>>> Emerging (1 of 4) www-plugins/yandex-browser-ffmpeg-codecs-bin-99.0.4844.84::yandex
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
>>> Downloading 'http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg-extra_99.0.4844.84-0ubuntu0.18.04.1_amd64.deb'
--2022-10-19 06:14:11--  http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-codecs-ffmpeg-extra_99.0.4844.84-0ubuntu0.18.04.1_amd64.deb
Resolving security.ubuntu.com... 185.125.190.39, 91.189.91.38, 185.125.190.36, ...
Connecting to security.ubuntu.com|185.125.190.39|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-19 06:14:11 ERROR 404: Not Found.

!!! Couldn't download 'chromium-codecs-ffmpeg-extra_99.0.4844.84-0ubuntu0.18.04.1_amd64.deb'. Aborting.
 * Fetch failed for 'www-plugins/yandex-browser-ffmpeg-codecs-bin-99.0.4844.84', Log file:
 *  '/var/tmp/portage/www-plugins/yandex-browser-ffmpeg-codecs-bin-99.0.4844.84/temp/build.log'

сейчас в ропозитории ubuntu

  | chromium-codecs-ffmpeg-extra_90.0.4430.72-0ubuntu0.16.04.1_amd64.deb | 2021-04-20 17:59 | 1.1M
  | chromium-codecs-ffmpeg-extra_90.0.4430.72-0ubuntu0.16.04.1_i386.deb | 2021-04-20 17:59 | 1.1M
  | chromium-codecs-ffmpeg-extra_105.0.5195.102-0ubuntu0.18.04.1_amd64.deb | 2022-09-15 13:18 | 1.1M
  | chromium-codecs-ffmpeg-extra_105.0.5195.102-0ubuntu0.18.04.1_i386.deb

**Comment by STrusov** [comment]
Попробуйте `media-video/ffmpeg-chromium`
Это рабочее решение для аналогичных браузеров. Работало с ЯБ, требовалось лишь создать ссылку вида
`/opt/yandex/browser-beta/libffmpeg.so -> /usr/lib64/chromium/libffmpeg.so.94`
Как обстоит дело в данный момент, не знаю, версия может не совпасть.

**Comment by an-kuznetsov** [comment]
Давайте я тогда полностью опишу проблему.
Поставить я пытаюсь www-client/yandex-browser-beta
У ниго в зависимостях стоит 
https://github.com/yandex-gentoo/overlay/blob/master/www-client/yandex-browser-beta/yandex-browser-beta-22.1.3.907_p1.ebuild
|| (
		www-plugins/yandex-browser-ffmpeg-codecs-bin
		www-plugins/yandex-browser-ffmpeg-codecs
	)

Первый не ставится по причине описанной выше
У второго следующая проблема:
https://github.com/yandex-gentoo/overlay/blob/master/www-plugins/yandex-browser-ffmpeg-codecs/yandex-browser-ffmpeg-codecs-20.8.0.864.ebuild
и видим в зависимостях sys-apps/hwids[usb(+)]
Смотрим на этот пакет и читаем https://github.com/gentoo/hwids
"This project is no longer active. [hwdata](https://github.com/vcrhonek/hwdata) is an active alternative."

И того. Как мне посавить yandex-browser в gentoo?

**Comment by STrusov** [comment]
Актуальная версия браузера [yandex-browser-stable-22.9.3.894-1.x86_64.rpm](https://repo.yandex.ru/yandex-browser/rpm/stable/x86_64/yandex-browser-stable-22.9.3.894-1.x86_64.rpm)
Здесь последние обновления были 7 месяцев назад.
Это говорит о том, что данный репозиторий заброшен. 

Максимум, что я мог сделать, это создать запрос на слияние https://github.com/yandex-gentoo/overlay/pull/19 изменений для поддержки `media-video/ffmpeg-chromium`. Он так и висит с января. Других прав у меня здесь нет.

Сейчас, что бы установить браузер, скачал rpm по ссылке выше, распаковал в `mc` (midnight commander) в `/opt` и `/usr` соответствующие каталоги из CONTENTS.cpio (для чего нужен `app-arch/rpm`). Скорее всего, можно точно так же установить и из [deb](https://repo.yandex.ru/yandex-browser/deb/pool/main/y/yandex-browser-stable/yandex-browser-stable_22.9.3.894-1_amd64.deb).

Создал ссылку на библиотеку
`# ln -s /usr/lib64/chromium/libffmpeg.so.102 /opt/yandex/browser/libffmpeg.so
`

Попробовал запустить:
```
$ yandex-browser-stable
Found ffmpeg: /opt/yandex/browser/libffmpeg.so
	avcodec: 3873124
	avformat: 3871845
	avutil: 3741797
FFmpeg version is too old. Need:
	avcodec: 3873892
	avformat: 3872868
	avutil: 3741796
```
Как видно, версия не подходит (решить это возможно, создав новую версию `media-video/ffmpeg-chromium`).

Что делать Вам? Проще всего запустить штатный скрипт браузера для установки кодеков: 

```
root /opt/yandex/browser # ./update-ffmpeg
--2022-10-21 14:34:09--  https://launchpadlibrarian.net/618703258/chromium-codecs-ffmpeg-extra_104.0.5112.101-0ubuntu0.18.04.1_amd64.deb
Распознаётся launchpadlibrarian.net… 185.125.189.228, 185.125.189.229, 2620:2d:4000:1001::8008, ...
Подключение к launchpadlibrarian.net|185.125.189.228|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 200 OK
Длина: 1161668 (1,1M) [application/x-debian-package]
Сохранение в: «/tmp/tmp.YaK0huBJdg/tmp.q4EtLwZ0f8»

/tmp/tmp.YaK0huBJdg/tmp.q4 100%[=====================================>]   1,11M  1,17MB/s    за 0,9s

2022-10-21 14:34:11 (1,17 MB/s) - «/tmp/tmp.YaK0huBJdg/tmp.q4EtLwZ0f8» сохранён [1161668/1161668]

FFMPEG codecs have been installed
```
Проверяем:
```
$ yandex-browser-stable
Found ffmpeg: /opt/yandex/browser/libffmpeg.so
	avcodec: 3873892
	avformat: 3872868
	avutil: 3741797
Ffmpeg version is OK! Let's use it.
```
Обновлять придётся так же вручную, но это, похоже, будет быстрее, чем через данный оверлей.

Обратите внимание, что раньше был yandex-browser-beta, а теперь yandex-browser-stable. В `~/.config` и `~/.cache` у нового свои каталоги, куда переносятся данные из старых. `www-client/yandex-browser-beta` можно удалить,

**Comment by an-kuznetsov** [comment]
Большое спасибо за развернутый ответ.
Очень не хотелось связываться с rpm, но чувствую придется.

**Comment by STrusov** [comment]
Имеющийся ebuild распаковывает deb, мне rpm привычнее, потому про него и писал.

Если не вручную, то пока вижу такие варианты:
1. Вы добавляете в `/etc/portage/repos.conf` ссылку на мой форк данного репозитория. Я его обновляю. Когда выходит новая версия браузера, кто-то меня пинает, я опять обновляю (там всей работы - актуализировать цифирки и, если нет подходящей версии `media-video/ffmpeg-chromium`, создать такую), проверяю работу кодеков на паре сайтов. Сам я ЯБ в Gentoo почти не использую, потому тестировать и следить за ним в «автоматическом режиме» сложно. Да и быстрее вот так вручную скачать, а больше никому не было надо, потому забросил.
2. Пишем куда-то в Gentoo, они меняют ссылки где следует. Наверное, такое имеет смысл только когда вариант 1 проверен и показал жизнеспособность.
3. Здесь появляется хозяин и вносит некотурую ясность по вопросу.

**Comment by vitaly-zdanevich** [comment]
Давайте в GURU пушить, чтобы все могли.
