### ISSUE TITLE
Would you like to move your ebuilds to Guru?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [yandex-gentoo/overlay#23]

**Comment by vitaly-zdanevich** [comment]
> no time for bureaucracy attached to contributions to GURU

I just push, without bureaucracy

And other people can improve it - I fixed invalid version (404) and X dependency https://github.com/gentoo/guru/tree/dev/www-client/yandex-browser

**Comment by vitaly-zdanevich** [comment]
Other people cannot fix ebuild here, but on GURU everybody can. For example - now in this repo - problem with ffmpeg https://github.com/yandex-gentoo/overlay/commit/f8cd1bf87449370993de6c02e441e4657fddec7d

**Comment by msva** [comment]
1) As with guru, where you would ask for access, you can also ask for access here
2) pushing in dev branch of guru is not enough for changes to apply to package in master (there is some bureaucracy neded sometimes for devs pushed changes to master (and "the mergers" decline merging for some reasons, and revert the changes, by the way).
3) I by myself don't forbid anyone to work on yowser (and maybe other yandex software) ebuilds in guru. Just I by myself feel better to maintain them there (and maybe just time-to-time port "stable" changes to guru (or maybe even in gentoo-repo)

**Comment by msva** [comment]
by the way, from the user perspective, I think they will prefer this repo over guru in following conditions:

a) they have only gentoo repo enabled 
b) they want to install **only** yowser
c) they would like to avoid another software from overlays to shadow (override) the one installed from gentoo repo.

**Comment by vitaly-zdanevich** [comment]
> As with guru, where you would need to ask for access to be able to push even to dev branch, you can also ask for access here 🤷

[Just create a ticket, one time](https://bugs.gentoo.org/831136)

> pushing in dev branch of guru is not enough for changes to apply to package in master

My experience - always on master after a few days.

Guru is more trustworthy and more secure - official repo, more people monitor it, they run automatic checks - virtual machine installs every ebuilds and automatically reports about errors.

**Comment by msva** [comment]
_(if any, my messages here is not an argumentation for using this repo as kinda "offcial source for that ebuilds" and ignore GURU. As I said above, I'm totally okay if anybody would maintain ebuilds from this repo also (or only) in guru.
even I myself maybe port ebuilds there from this repo time-to-time.
But I personally using this overlay as kinda "sandbox", and it is more comfortable for me to have it in separate repo, than with any other stuff in guru)_


> Just create a ticket, one time

As for here :grinning: 


> Guru is more trustworthy and more secure - official repo

Well. Both "Yes" and "No".  
All of this is true, but it's "officiality" is kinda lesser then gentoo repo's one.
And QA policies in guru is far more "lighter" than in Gentoo repo.

I'd say GURU is analog of ArchLinux's AUR (although, GURU still have more QA than AUR, lol)
And separate thematic overlays like this (or like my personal) - are like Ubuntu's PPAs.

They both have good usecases.
