### ISSUE TITLE
ffmpeg-chromium-120 is missing from the gentoo repository

### ISSUE THREAD

**Issue by vostok01** [yandex-gentoo/overlay#28]
Yandex browser cannot be installed. The media-videos/ffmpeg-chromium-120 package required for installation is missing from the gentoo repository.

**Comment by msva** [comment]
Fixed in https://github.com/yandex-gentoo/overlay/commit/b37a6aa4eb1297676319c80e44a11def4e4b4a9b

**Comment by vostok01** [comment]
ffmpeg-chromium-122 is also missing from the gentoo repository.

**Comment by vostok01** [comment]
ffmpeg-chromium-122 is also missing from the gentoo repository.

**Comment by msva** [comment]
:hear_no_evil: 

Sorry, I didn't synced working copy of gentoo repo for a long time already (as I preparig few PRs there)

And then just bumped the PVs of ffmpeg-chromium in ebuild(s) according to the Chromium version that version of yowser are built on top of (they are anyway incompatible with any newer.

By the way, it seems, it (yowser) has some internal (statically linked? :thinking:) library which it falls back on when it fails to find libffmpeg.so, or if version it found is too new.
(and even 124 is too new for stable and corporate ones).
But (at least corporate) successfully falls back on "internal" (staticaly linked, I guess? :thinking:) library (either with broken symlinkand when it found 124+ which are "too new").


So, I'd try to temporary make stable and corporate to depend of 124 (minimal available in gentoo), but it will not use them anyway...

Please, check, if it will work for you.

Also, I'd recomend to temporary set `USE=-ffmpeg-codecs` for now, to don't depend on `ffmpeg-chromium` at all, as they anyway will not use it (except for beta, which is based on chromium-124).
And, I guess, next releases would be based onn 124 and will be ok with ffmpeg-chromium-124.


Anyway, please, checkif currennt fix is working for you.
